[workspace]
authors = ["Jeremy Trimble <jeremy.trimble@gmail.com>"]
channels = ["conda-forge"]
name = "specview"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
pyqtgraph = ">=0.13.7,<0.14"
pyqt = ">=5.15.11,<6"

[pypi-dependencies]
sigmf = ">=1.2.10, <2"
numpy = "*"
scipy = ">=1.16.0, <2"
specview = {path=".", editable=true}
