[project]
name = "specview"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.3.1",
    "platformdirs>=4.3.8",
    "pydantic>=2.11.7",
    "pyqt5>=5.15.11",
    "pyqtgraph>=0.13.7",
    "pyqtschema>=0.2.0",
    "scipy>=1.16.0",
    "sigmf>=1.2.10",
]

[dependency-groups]
build = [
    "pyinstaller>=6.16.0",
    "specview",
]
dev = [
    "pytest>=8.4.1",
    "mypy>=1.18.2",
    "pytest-cov>=7.0.0",
    "specview",
]

[tool.uv.sources]
specview = { workspace = true }

[tool.pytest.ini_options]
addopts = "--cov=src/specview --cov-report=term --cov-report=html"
testpaths = [
    "tests"
]

# Declare a build backend so that uv sync --group dev causes specview to be installed editably
[build-system]
requires = ["uv_build>=0.9.4,<0.10.0"]
build-backend = "uv_build"

# TODO: make the build backend generate the version info for a wheel file
