INTERVAL_ROI_COLOR = "#6060FF"
ANNOTATION_ROI_COLOR = "#F04040C0"

SELECTED_ANNOTATION_ROI_COLOR = "#4080FFC0"

# QSettings constants for application state persistence
SETTINGS_ORGANIZATION = "SpecView"
SETTINGS_APPLICATION = "SpecView"