name: Build Specview Executables

on:
  push:
    branches:
      - 'main'

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, macos-latest, windows-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install uv
          uv sync --group build --group dev

      - name: Build with PyInstaller
        run: |
          uv run pyinstaller --clean  specview.spec

      - name: Upload executable artifact
        uses: actions/upload-artifact@v4
        with:
          name: specview-${{ runner.os }}
          path: |
            dist/*
